title: OpenNebula Training Lab Guides
logo: "assets/common/logo.png"
description: Step-by-step OpenNebula Lab instructions
remote_theme: just-the-docs/just-the-docs
baseurl: ""
url: "https://alpeon.github.io"
back_to_top: true
back_to_top_text: "Up!"
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true